[package]
name = "hello-pingora"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1"
env_logger = "0.11"
http = "1"
log = "0.4"
pingora = { version = "0.3", features = [ "lb" ] }
